### ISSUE TITLE
Clean-up Build Process "blogDir"

### ISSUE THREAD

**Issue by arntsonl** [OpenStickCommunity/Site#38]
Can we clean up the build process to get rid of "blogDir" dependency?

![image](https://github.com/OpenStickCommunity/Site/assets/7754729/a76e7408-e538-4b60-92ec-908713fc54ec)

**Comment by InfraredAces** [comment]
This warning is due to not having a `blog` directory in the root. This can be resolved by having an empty blog directory even though we have blog routing disabled in [`docusaurus.config.js`](https://github.com/OpenStickCommunity/Site/blob/440633964fb3ff31d4019ba477d7305a9ff90204/docusaurus.config.js#L40). 

Even if this change it not made, this warning should not have an effect on the build process as it is.
